// ===== TEMPLATES DE MÉTADONNÉES PAR PRODUIT =====
export const METADATA_TEMPLATES = {
  'Meubles de douches': {
    descriptions: [
      'Meuble vasque suspendu 2 tiroirs',
      'Meuble salle de bain 3 portes',
      'Colonne de rangement salle de bain',
      'Meuble sous vasque 1 porte',
      'Armoire miroir lumineuse',
      'Meuble TV salle de bain',
      'Étagère salle de bain en verre',
      'Meuble lavabo 2 vasques',
    ],
    prices: ['199€', '249€', '299€', '349€', '399€', '459€', '499€', '599€'],
    references: [
      'MDB-001',
      'MDB-002',
      'MDB-003',
      'MDB-004',
      'MDB-005',
      'MDB-006',
      'MDB-007',
      'MDB-008',
    ],
  },
  Tablettes: {
    descriptions: [
      'Table basse en bois massif',
      'Table de salon en verre',
      "Table d'appoint ronde",
      'Table de bout carrée',
      "Console d'entrée",
      'Table de salle à manger 6 places',
      'Table extensible 8 places',
      'Table de jardin',
    ],
    prices: ['89€', '129€', '159€', '199€', '249€', '299€', '399€', '499€'],
    references: [
      'TAB-001',
      'TAB-002',
      'TAB-003',
      'TAB-004',
      'TAB-005',
      'TAB-006',
      'TAB-007',
      'TAB-008',
    ],
  },
  Canapés: {
    descriptions: [
      'Canapé 3 places en cuir',
      'Canapé 2 places en tissu',
      "Canapé d'angle convertible",
      'Fauteuil club vintage',
      'Canapé modulable',
      'Méridienne',
      'Canapé lit 2 places',
      "Banquette d'entrée",
    ],
    prices: [
      '599€',
      '799€',
      '999€',
      '1299€',
      '1499€',
      '1799€',
      '1999€',
      '2499€',
    ],
    references: [
      'CAN-001',
      'CAN-002',
      'CAN-003',
      'CAN-004',
      'CAN-005',
      'CAN-006',
      'CAN-007',
      'CAN-008',
    ],
  },
  'Serrure de portes': {
    descriptions: [
      'Serrure 3 points',
      'Serrure à gorges',
      'Serrure encastrée',
      'Verrouillage multipoints',
      'Serrure électronique',
      'Serrure de sécurité',
      'Cylindre européen',
      'Serrure à levier',
    ],
    prices: ['39€', '59€', '79€', '99€', '129€', '159€', '199€', '249€'],
    references: [
      'SER-001',
      'SER-002',
      'SER-003',
      'SER-004',
      'SER-005',
      'SER-006',
      'SER-007',
      'SER-008',
    ],
  },
  'Évier & robinets': {
    descriptions: [
      'Évier inox 1 bac',
      'Évier granit 2 bacs',
      'Robinier mitigeur',
      'Évier sous plan',
      'Évier céramique',
      'Robinet à bec haut',
      'Évier à égouttoir',
      'Robinet à levier',
    ],
    prices: ['49€', '79€', '99€', '129€', '159€', '189€', '219€', '259€'],
    references: [
      'EVI-001',
      'EVI-002',
      'EVI-003',
      'EVI-004',
      'EVI-005',
      'EVI-006',
      'EVI-007',
      'EVI-008',
    ],
  },
}

// Fallback pour les produits inconnus
export const DEFAULT_TEMPLATE = {
  descriptions: [
    'Produit de qualité',
    'Article design',
    'Modèle contemporain',
    'Création artisanale',
  ],
  prices: ['99€', '149€', '199€', '299€'],
  references: ['ART-001', 'ART-002', 'ART-003', 'ART-004'],
}
